export const products = [
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone XL',
        price: 799,
        description: 'A large phone with one oh the best screens',
        heading1: 'サンプルテキスト１',
        heading2: 'サンプルテキスト２',
        heading3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト',
        headingtext2: 'Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.',
        headingtext3: 'サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2',

    },
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone Mini',
        price: 699,
        description: 'A great phone with one of the camera',
        heading1: 'サンプルテキスト１',
        heading2: 'サンプルテキスト２',
        heading3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト',
        headingtext2: 'Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.',
        headingtext3: 'サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2',
    },
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone Standard',
        price: 299,
        description: '',
        heading1: 'サンプルテキスト１',
        heading2: 'サンプルテキスト２',
        heading3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト',
        headingtext2: 'Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.',
        headingtext3: 'サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2',
    },
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone Standard2',
        price: 199,
        description: '',
        heading1: 'サンプルテキスト１',
        heading2: 'サンプルテキスト２',
        heading3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト  サンプルテキスト',
        headingtext2: 'Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.',
        headingtext3: 'サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2  サンプルテキスト2',
    }
];